### ISSUE TITLE
Translate strings Components and Get Started

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-api-i18n#15]
Components and GetStarted should be translated as well:

![image](https://user-images.githubusercontent.com/11193764/48914244-7d976380-ee83-11e8-962e-2229d762d855.png)

**Comment by yoshimis** [comment]
@ViktorSlavov Components should be replaced with コンポーネント and GET STARTED should be replaced with はじめに in Japanese.
Also the following urls should be used.
Components - https://jp.infragistics.com/products/ignite-ui-angular
GET STARTED - https://jp.infragistics.com/products/ignite-ui-angular/getting-started

**Comment by Aleksandyr** [comment]
The [issue](https://github.com/IgniteUI/igniteui-angular/issues/3161) was logged into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular).
