### ISSUE TITLE
EN strings appearing in the JP generated documentation

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#18]
The strings 
"optionally, if the search should be case sensitive (defaults to false)."
"optionally, if the text should match the entire value (defaults to false)."
"if true clears the current selection"
are being displayed on staging:

https://staging.infragistics.local/angular-docs/typescript/classes/IgxGridComponent.html
but are not present in the https://github.com/IgniteUI/igniteui-angular-api-i18n/blob/master/typedoc/en/lib/grids/IgxGridComponent.json

The string "Returns a reference to the filter cell of the column." is present on staging:
https://staging.infragistics.local/angular-docs/typescript/classes/IgxColumnComponent.html

but it's not found in 
https://github.com/IgniteUI/igniteui-angular-api-i18n/blob/master/typedoc/en/lib/grids/IgxColumnComponent.json

Why are these strings also showing on JP staging even though they weren't in the corresponding JP json file (IgxGridComponent.json)?
https://jp.staging.infragistics.local/angular-docs/typescript/classes/IgxGridComponent.html

If possible the JP build should contain only strings which are present in the JP folder of the typedoc folder:
https://github.com/IgniteUI/igniteui-angular-api-i18n/tree/master/typedoc/ja/lib

**Comment by zdrawku** [comment]
As we discussed with @valadjov we are going to test this issue once JP content is translated entirely basde on the EN content update from Friday.

**Comment by Aleksandyr** [comment]
@valadjov We have resolved all issues except the second one.
We have logged [issue ](https://github.com/IgniteUI/igniteui-angular-api-i18n/issues/21) for it, so I'm going to close the current one.
