### ISSUE TITLE
Unresolved strings in the EN and JP documentation

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#27]
1. Open https://infragistics.com/angular-docs/typescript/classes/calendarhammerconfig.html
https://infragistics.com/angular-docs/typescript/classes/groupedrecords.html

2. Navigate to Properties -> events for the first page and Properties -? length for the second one.
3. Examine the Defined in string

Actual result:
The "Defined in:" is:
Defined in E:/BuildAgents/D/_work/32/s/node_modules/@angular/platform-browser/src/dom/events/hammer_gestures.d.ts:45

Defined in E:/BuildAgents/D/_work/32/s/node_modules/typescript/lib/lib.es5.d.ts:1139

Expected result:
The "Defined in:" should be something like:
Defined in lib/calendar/calendar.component.ts:44

**Comment by Aleksandyr** [comment]
@valadzhov This should be hidden. I have logged the [issue ](https://github.com/IgniteUI/igniteui-angular/issues/3483 )into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository.

**Comment by valadzhov** [comment]
@yoshimis The bug is logged under igniteui-angular repository now.
