### ISSUE TITLE
sass: link on secondary nav in JP leads to EN product page

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-angular-api-i18n#28]
Step to reproduce:
1. open JP sass help page: https://jp.infragistics.com/products/ignite-ui-angular/docs/sass/
2. click "Ignite UI for Angular" link on secondary nav

expected result: 
it should lead to https://jp.infragistics.com/products/ignite-ui-angular

actual result:
it leads to https://www.infragistics.com/products/ignite-ui-angular

![sass](https://user-images.githubusercontent.com/14284406/50318660-d3ecd600-0505-11e9-91f4-e33396c926e0.JPG)

**Comment by Aleksandyr** [comment]
The [issue ](https://github.com/IgniteUI/igniteui-angular/issues/3516) was logged into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository.
