### ISSUE TITLE
Visible @hidden tag due to bad json structure

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#30]
1. Open https://infragistics.com/angular-docs/typescript/interfaces/hierarchicalstate.html

The tag @hidden is visible and shouldn't be. According to Alex this is due to bad json structure.

**Comment by Aleksandyr** [comment]
This issue was [logged](https://github.com/IgniteUI/igniteui-angular/issues/3523) into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular)
