### ISSUE TITLE
Implement typedoc and sassdoc versioning

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-api-i18n#5]
We need to think of a way to add a versioning to the current document generation.

**Comment by zdrawku** [comment]
@SlavUI could you add this to your planner, we need to spend time on this because will impact both typedoc and sassdoc document generations and the whole Style and Api documentation.

**Comment by Aleksandyr** [comment]
@SlavUI @zdrawku The [issue](https://github.com/IgniteUI/igniteui-angular/issues/3532) was logged into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository as the changes would apply there.
