### ISSUE TITLE
Sample code snippet is wrong in JP igx-grid drag and drop help

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-api-i18n#53]
Open EN help:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_drag.html
![image](https://user-images.githubusercontent.com/33947244/69020173-f7125500-09f6-11ea-8da3-2661571ffdde.png)

Open JP help:
https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_drag.html
![image](https://user-images.githubusercontent.com/33947244/69020241-30e35b80-09f7-11ea-9151-945f5969446d.png)

Expected:
(onEnter), (onLeave) and (onDrop) in JP help should be (enter), (leave) and (dropped) respectively.

**Comment by norikois** [comment]
This is due to a breaking change in IgxDrop in 8.2.0
https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.0

**Comment by norikois** [comment]
Sorry for adding comments one after another..
In the same JP help page, there is also a place where old event names are used.
Could you take care of them, too?

EN help:
![image](https://user-images.githubusercontent.com/33947244/69020923-815bb880-09f9-11ea-923d-e36857f7aa87.png)

JP help
![image](https://user-images.githubusercontent.com/33947244/69021039-dac3e780-09f9-11ea-9e08-ddfccbac2fc3.png)

**Comment by randriova** [comment]
Closing this, as the reported issues have been resolved.
