### ISSUE TITLE
Possible formatting issues

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#8]
The following strings seem badly formatted:

https://www.infragistics.com//angular-docs/typescript/classes/igxcolumncomponent.html
Under set sortStrategy(classRef: any): void

`typescript this.column.sortStrategy = new CustomSortingStrategy().
class CustomSortingStrategy extends SortingStrategy { ... } `

Unde autosize
let column = this.grid.columnList.filter(c => c.field === 'ID')[0]; column.autosize(); `

https://infragistics.com//angular-docs/typescript/classes/igxcolumngroupcomponent.html#summaries
Under set sortStrategy(classRef: any): void

Sets the column sortStrategy. `typescript this.column.sortStrategy = new CustomSortingStrategy().

class CustomSortingStrategy extends SortingStrategy { ... } `

https://www.infragistics.com//angular-docs/typescript/classes/igxgridbasecomponent.html#page
Under Defined in lib/grids/grid-base.component.ts:340
<igx-grid #grid [data]="Data" [paging]="true" [page]="5" [autoGenerate]="true">

https://www.infragistics.com//angular-docs/typescript/classes/igxgridcomponent.html#autogenerate
Under dropAreaTemplate
`html <igx-grid [dropAreaTemplate]="dropAreaRef"> <igx-column [groupable]="true" field="ID">

<ng-template #myDropArea> Custom drop area! 
```ts

https://www.infragistics.com//angular-docs/typescript/classes/igxgridcomponent.html#autogenerate
Under hiddenColumnsCount
`typescript const hiddenCol = this.grid.hiddenColumnsCount;

Under hiddenColumnsText
`typescript const hiddenColText = this.grid.hiddenColumnsText;

Under page
<igx-grid #grid [data]="Data" [paging]="true" [page]="5" [autoGenerate]="true">

Under findPrev
this.grid.findPrev("financial");
`
https://www.infragistics.com//angular-docs/typescript/classes/igxtreegridcomponent.html#page
Under page:
<igx-grid #grid [data]="Data" [paging]="true" [page]="5" [autoGenerate]="true">

**Comment by Aleksandyr** [comment]
@valadzhov Seems that the problems came from the comments of the source code. Which means that those changes should be made into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository.

**Comment by Aleksandyr** [comment]
The [issue](https://github.com/IgniteUI/igniteui-angular/issues/3183) was logged into [igniteui-angular](https://github.com/IgniteUI/igniteui-angular) repository.
