### ISSUE TITLE
Strings showing in EN for which JP localization has been provided

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-api-i18n#9]
All the strings from "onRowSelectionChange" to "width" and the strings under "endEdit" in the following page are in EN even though localization has been provided:
https://jp.infragistics.com/products/ignite-ui-angular/docs/typescript/classes/igxgridcomponent.html

**Comment by Aleksandyr** [comment]
@valadzhov It seems that the structure of the JSON file wasn't correct. Probably the brackets were incorrectly placed during the translations and merge changes. Please be very careful with the structure per every file because as you can see we hardly understand that the problem is there.
